name: "aws s3 action"

description: "Uploading a File to AWS S3"

inputs:
  aws-access-key-id:
    description: "Your aws access key id"
    required: true

  aws-secret-access-key:
    description: "Your aws secret access key"
    required: true

  aws-region:
    description: "Specify the Region"
    required: true

  aws-bucket:
    description: "Backet name"
    required: true    

  filename:
    description: "file name"
    required: true    
    
runs:
  using: "docker"
  image: "Dockerfile"